import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/src/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className={` ${styles.main} ${inter.className}`}>

					<h1 className={styles.h1}>
						Welcome to Next.js
					</h1>

					<ul className={styles.post}>
						<li>
							<p className={styles.postsContent}>
								I’ am working on figma  trying to design a new website that shows all my tweets
							</p>
							<p className={styles.postsDate}>
								2/26/2024
							</p>
						</li>
						<li>
							<p className={styles.postsContent}>
								I’ am working on figma  trying to design a new website that shows all my tweets
							</p>
							<p className={styles.postsDate}>
								2/26/2024
							</p>
						</li>
						<li>
							<p className={styles.postsContent}>
								I’ am working on figma  trying to design a new website that shows all my tweets
							</p>
							<p className={styles.postsDate}>
								2/26/2024
							</p>
						</li>
					</ul>

				</main >
			</div>
		</>
	);
}
